# Generated by Django 6.0.4 on 2026-09-07

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('campanias', '0004_campania_centro_salud'),
    ]

    operations = [
        migrations.AddField(
            model_name='campania',
            name='cupo_maximo',
            field=models.PositiveIntegerField(
                blank=True,
                null=True,
                validators=[django.core.validators.MinValueValidator(1)],
            ),
        ),
    ]
