# Generated by Django 6.0.4 on 2026-09-07

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name='Contacto',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('email', models.EmailField(max_length=254)),
                ('asunto', models.CharField(max_length=100)),
                ('mensaje', models.CharField(max_length=500)),
                ('tracked', models.BooleanField(default=False)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'contactos',
                'ordering': ['tracked', '-fecha_creacion'],
            },
        ),
    ]
