# Generated by Django 6.0.4 on 2026-09-07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('usuarios', '0004_alter_usuario_options_alter_usuario_apellido_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='fecha_nacimiento',
            field=models.DateField(default=datetime.date(1990, 1, 1)),
            preserve_default=False,
        ),
    ]
